# Define the keywords to search for RCT

KEYWORDS = [
    "quasi",
    "Experimental",
    "Controlled",
    "Trial",
    "trial",
    "controlled trial",
    "RCT",
    "rct",
    "crct",
    "cRCT",
    "experimental",
    "Randomised",
    "Cluster-randomised",
    "cluster",
    "Randomisation",
    "controlled trial",
    "controlled",
    "RCT",
    "rct",
    "crct",
    "cluster-RCT",
    "quasi-experimental",
    "cRCT",
    "Randomised",
    "Cluster-randomised",
    "cluster",
]
