# Define the keywords to search for RCT
KEYWORDS = [
    "quasi",
    "Experimental",
    "Controlled",
    "Trial",
    "trial",
    "controlled trial",
    "RCT",
    "rct",
    "crct",
    "cRCT",
    "experimental",
    "Randomised",
    "Cluster-randomised",
    "cluster",
    "Randomisation",
    "controlled trial",
    "controlled",
    "RCT",
    "rct",
    "crct",
    "cluster-RCT",
    "quasi-experimental",
    "cRCT",
    "Randomised",
    "Cluster-randomised",
    "cluster",
]


# used in table parser
word_end_strings = [
    "about",
    "around",
    "and/or",
    "whether",
    "in",
    "as",
    "to",
    "has",
    "will",
    "have",
    "been",
    "was",
    "were",
    "over",
    "the",
    "a",
    "an",
    "under",
    "less than",
    "more than",
    "to",
    "in",
    "were",
    "and",
    "by",
    "of",
    "is",
    "within",
    "nearly",
    "roughly",
    "almost",
    "below",
    "exceeds",
    "above",
    "beyond",
    "against",
    "among",
    "between",
    "during",
    "per",
    "with",
    "without",
    "equals",
    "from",
]

# used in table parser
char_end_strings = [";", ",", "+", "=", ":", "/", "-"]
